/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FirmwareRouteImport } from './routes/firmware'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BikesIdIndexRouteImport } from './routes/bikes.$id.index'
import { Route as BikesIdTopicsRouteImport } from './routes/bikes.$id.topics'
import { Route as BikesIdKioskRouteImport } from './routes/bikes.$id.kiosk'

const FirmwareRoute = FirmwareRouteImport.update({
  id: '/firmware',
  path: '/firmware',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesIdIndexRoute = BikesIdIndexRouteImport.update({
  id: '/bikes/$id/',
  path: '/bikes/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesIdTopicsRoute = BikesIdTopicsRouteImport.update({
  id: '/bikes/$id/topics',
  path: '/bikes/$id/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesIdKioskRoute = BikesIdKioskRouteImport.update({
  id: '/bikes/$id/kiosk',
  path: '/bikes/$id/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/firmware': typeof FirmwareRoute
  '/bikes/$id/kiosk': typeof BikesIdKioskRoute
  '/bikes/$id/topics': typeof BikesIdTopicsRoute
  '/bikes/$id/': typeof BikesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/firmware': typeof FirmwareRoute
  '/bikes/$id/kiosk': typeof BikesIdKioskRoute
  '/bikes/$id/topics': typeof BikesIdTopicsRoute
  '/bikes/$id': typeof BikesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/firmware': typeof FirmwareRoute
  '/bikes/$id/kiosk': typeof BikesIdKioskRoute
  '/bikes/$id/topics': typeof BikesIdTopicsRoute
  '/bikes/$id/': typeof BikesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/firmware'
    | '/bikes/$id/kiosk'
    | '/bikes/$id/topics'
    | '/bikes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/firmware'
    | '/bikes/$id/kiosk'
    | '/bikes/$id/topics'
    | '/bikes/$id'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/firmware'
    | '/bikes/$id/kiosk'
    | '/bikes/$id/topics'
    | '/bikes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  FirmwareRoute: typeof FirmwareRoute
  BikesIdKioskRoute: typeof BikesIdKioskRoute
  BikesIdTopicsRoute: typeof BikesIdTopicsRoute
  BikesIdIndexRoute: typeof BikesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/firmware': {
      id: '/firmware'
      path: '/firmware'
      fullPath: '/firmware'
      preLoaderRoute: typeof FirmwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes/$id/': {
      id: '/bikes/$id/'
      path: '/bikes/$id'
      fullPath: '/bikes/$id/'
      preLoaderRoute: typeof BikesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes/$id/topics': {
      id: '/bikes/$id/topics'
      path: '/bikes/$id/topics'
      fullPath: '/bikes/$id/topics'
      preLoaderRoute: typeof BikesIdTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes/$id/kiosk': {
      id: '/bikes/$id/kiosk'
      path: '/bikes/$id/kiosk'
      fullPath: '/bikes/$id/kiosk'
      preLoaderRoute: typeof BikesIdKioskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  FirmwareRoute: FirmwareRoute,
  BikesIdKioskRoute: BikesIdKioskRoute,
  BikesIdTopicsRoute: BikesIdTopicsRoute,
  BikesIdIndexRoute: BikesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
